server:
  port: 80

# Spring Boot 的数据源配置
spring:
  datasource:
    name: crm
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20



# Mybatis的配置
mybatis:
  #指定mybatis映射文件xml的位置是在resources/mapping/下
  mapper-locations: classpath:mapping/*.xml
  # 指定实体类的包
  type-aliases-package: com.tx.zhcrm.entity

